### ISSUE TITLE
datasets--sharing info

### ISSUE THREAD

**Issue by LeeDelaino** [edquant/edh7916#12]
Hi All--I wanted to share this with you, hope it's OK, Ben-- I found that I could go to: http://www.fldoe.org/accountability/  and download .csv files of data on any number of topics.  They have a tool where you can build your own report (at least I found I could in the PK-20 data warehouse portal).  

From the link above, click on Data Systems.  Look through the different options there.  In the PK-20 portal there was a quick start guide that showed how to download the .csv and .xlsx files.  Some of the others seemed to be dead ends or had a couple of files, but I didn't search much further b/c I was after the 2-year college info.

**Comment by btskinner** [comment]
@edquant/team_class: adding class team so that people see this in case they are interested. 

Per using this portal (or another): keep in mind that for replication purposes, you have to record every click you make to get the data. You also shouldn't do "analyses" using a data portal (means, summaries, _etc_). Get the data as close to "raw" as possible.

That said, if you are interested in Florida data, this seems to be a nice resource. Thanks, @LeeDelaino!
