### ISSUE TITLE
Assignment 2- One dot v. two dots in step 4 objects/macros AND stuck on step 9

### ISSUE THREAD

**Issue by taylorburtch** [edquant/edh7916#2]
Hello everyone,
When working on the assignment, we discovered that when following our printouts from class (two dots in the object/macro examples), we ran into issues with **step 7** (the program could not locate the data file we needed). We got it to work by going back up into our macros and changing our object labels to one dot, I _think_ telling the computer to look at a different (correct) level. We of course had to highlight and re-run the changes before the adjustment would make **step 7** work. I hope this is correct?

Side note to Ben (and potentially to other colleagues who had trouble in the last 10 minutes of class), I did not have the updated test score data file, so I had to use the original between **steps 7 and 8**. For some reason, while I expected to find the updated data file when I pulled updates despite my falling behind in class, it was not there. I hope this is okay! Niki had to do this as well. 

-Taylor, Jaime, Niki & Lee

**Comment by taylorburtch** [comment]
Reached impasse with **step 9**-- despite teamwork, google, Git "Help," extensive tinkering and the "HINT" in the assignment. It is clear that we need to somehow manipulate the former column (test_scores_new_2) using brackets in some way. Anyone get this figured out?

**Comment by btskinner** [comment]
@taylorburtch, @jharsell, @brightstone1, and @LeeDelaino (and others) per your question about the updated data file (`test_scores_updated.RDS`): I did not push this to your repos. This should be what you saved after running through the script in class. That said, you technically don't need `test_scores_updated.RDS` --- you can use the original `test_scores.RDS` to do the assignment (as I think you did). Just don't overwrite the original file when you save at the end (step 10).

If stuck on **step 7**, you can either:
1. change the relative paths (as it seems you did), or
2. check your working directory with `getwd()` and change with `setwd()` so that the relative path works

Not to be too meta, but a relative path works either by changing (1) _how you get there from here_ or (2) where _here_ is. (1) means change the path while (2) means changing the working directory.

**Comment by btskinner** [comment]
And per your second question, @taylorburtch, yes you are on the right track with column + bracket (`[]`) notation being a solution.

**Comment by taylorburtch** [comment]
At it again... but Lee and I can still not figure out how to do step 7. I am continually searching words/phrases like "copy" or "copy data" in the R search but it is returning things about databases, remotes, etc. and I am not sure how "column" and/or "data sets" (which I believe is what we are calling "test_scores_new_2") factor into this. Progress is very, very slow.

**Comment by btskinner** [comment]
In **step 7**, you should read in the data just like we did in class. The only real difference will be if you saved an updated data set during class (`test_scores_updated.RDS`); in that case, you should modify the lines from the class example to read in that data file instead.

**Comment by btskinner** [comment]
@edquant/team_class, I've added `organizing_hw_example.R` to your `scripts` directory. I've added a lot of notes to explain what I've done along the way. I show three different ways to solve **step 9**, each one a little more succinct. The first one is just fine, the second one a little better, and the third one more advanced. Understanding how the first and second work are all I expect right now.

If you still have questions, please post them here, come to office hours, or set up a time to meet with me. I'm closing this issue now, but again, feel free to reopen if you have more questions.
