### ISSUE TITLE
Error: C stack usage  15925264 is too close to the limit

### ISSUE THREAD

**Issue by jharsell** [edquant/edh7916#3]
Hi all,

Has anyone else seen this message? I gave it a google and the following fix is what was on stack overflow:
```
[XSI] [Option Start] #include <sys/resource.h>

int getrlimit(int resource, struct rlimit *rlp);
int setrlimit(int resource, const struct rlimit *rlp)
```
But I do not know if this is accurate or what I should set the limit to. I am on step 9 and cannot proceed with this issue.

Thanks!
Jaime

**Comment by btskinner** [comment]
@jharsell: really gnarly answers like this often mean

1. a bad installation of R or a package
2. some very off label R scripting

Are you still having this error? If so, can you share the code you ran when it occurred?

**Comment by jharsell** [comment]
Hi Dr. Skinner,

My apologies for my late response. I was in Tampa and forgot my power cord for my laptop. It appears I can no longer run any scripts. I was working on step 8 and 9 of this week's assignment. I attached a screenshot of the issue and the script, I also pushed what I could from the assignment.

![Stack Usage Error](https://user-images.githubusercontent.com/59618374/72767763-209c5800-3bc3-11ea-8446-669bfac975b8.PNG)

**Comment by btskinner** [comment]
@jharsell, without seeing the full history of what you've run, it's difficult to tell. My guess is that you've got a recursive function running. That means you've ended up with a function that keeps calling itself until your computer runs out of memory. If you haven't already, shut down RStudio and run your scripts lines fresh.

Also, don't run `<dataframe>$<test_scores_new_2> <- function(<old_socres_column>, <ratio>)`. That's just a bit of [pseudo code](https://en.wikipedia.org/wiki/Pseudocode) meant to give you the idea of what the function is doing. That's why it's commented out. That might be the point of the problem.

**Comment by btskinner** [comment]
@jharsell, are you still having this issue?

**Comment by jharsell** [comment]
Hi Dr. Skinner,

Please pardon my response delay – I have not had the opportunity to revisit the assignment because of my work schedule this week. However,  as of Sunday evening, I could no longer run any script without the error.


[cid:image23cd62.PNG@af9bab34.48910acb]<http://>

Jaime Harsell | Senior Assistant Director for Career Engagement
Career Connections Center
UF Division of Student Affairs
J. Wayne Reitz Union, Suite 1300 | PO Box 118507
Gainesville, FL 32611-8507
Phone 352-294-3928 | jharsell@ufsa.ufl.edu
National Award Winning Career Services! career.ufl.edu<https://career.ufl.edu/> | Twitter<https://twitter.com/ufcareercenter>
Pronouns: She, Her, Hers

**Comment by btskinner** [comment]
For future people who may have this error, it seems it was just a borked R/RStudio installation. Deleting and reinstalling R and RStudio seemed to fix the problem.
