### ISSUE TITLE
Cannot open .dta (Stata) file?

### ISSUE THREAD

**Issue by nszekeres** [edquant/edh7916#36]
Hi, Dr. Skinner - I'm trying to do assignment 8 but I can't read in the data... it keeps telling me it can't find function for "read_dta"? I've closed R studio several times and even rebooted my computer... do you know if there is a specific library I have to manually call to use this function??

`package ‘survey’ successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\Users\Naomi\AppData\Local\Temp\RtmpS8mU6p\downloaded_packages
> dat_dir <- file.path("..", "data")
> df <- read_dta(file.path(dat_dir, "els_plans.dta"))
Error in read_dta(file.path(dat_dir, "els_plans.dta")) : 
  could not find function "read_dta"
`

Thanks,
Naomi

**Comment by nszekeres** [comment]
I think installing Haven fixed it...

**Comment by btskinner** [comment]
@nszekeres: yes, you need to load `library(haven)` in order to read in data from Stata (or SPSS or SAS). It's one of those -in-between packages I mentioned. It's part of the tidyverse and installed when you do `install.packages("tidyverse")`, but isn't of the core packages loaded when you call `library(tidyverse)`. That's why you have to load it separately.

**Comment by nszekeres** [comment]
@btskinner - thanks...
