### ISSUE TITLE
Error in pull down

### ISSUE THREAD

**Issue by LeeDelaino** [edquant/edh7916#7]
I am getting this error when I open R Studio and try to pull:
![image](https://user-images.githubusercontent.com/59539480/73075585-45762100-3e8a-11ea-8ee9-7c3876ba63ec.png)
  What I've been able to find online suggests commands i'm not sure I should do---for example:
```
git add * 
git stash
git pull
```
Not sure what to do and can't get to work until I fix/

**Comment by btskinner** [comment]
@LeeDelaino, here's what this means: those files have changed on your computer since I initially added them while at the same time changed on the remote repo (GitHub). In other words, they are out of sync in such a way that git aborts the pull b/c it doesn't have a clear solution on how to handle the difference.

It may be out of sync simply because you've opened them (in the case of the pdf files, though I'm not 100% sure on that) or if you've saved changes to them (`hsls_small.csv` or `dw_one.R`) on your computer. Regardless, git is telling you what to do (though in an unclear way):

> Please move or remove them before you merge

The easiest solution is to 

1. move those files out of your student repo (which it looks like you've called `edh7916`). Open the folder on your computer in the file manager and drag and drop them somewhere else (the desktop is a good temporary spot). 
1. Next, stage/commit your changes. 
1. Finally, pull down

If everything worked as it should, you should see those files again in your `edh7916` repo again since they are class files that I put in there. You should be good to go and can delete those files you moved out in the first step above.

If you took notes during class in `dw_one.R` that you would like to keep, however, rename it to something else --- _i.e._, `dw_one_notes.R` --- and move it back to the `scripts` folder. You can state/commit/push it like normal and no changes I make in the future will affect it.

Follow up with me to let me know if this works or not. If not, we've got some other solutions we can try.

**Comment by LeeDelaino** [comment]
Seems to have worked--thanks for  your help.

**Comment by btskinner** [comment]
Great! Closing, but reopen if the issue pops up again.
