### ISSUE TITLE
Homework not showing up to "commit"

### ISSUE THREAD

**Issue by taylorburtch** [edquant/edh7916#8]
I am trying to stage and commit as I work on the homework, but the file is not showing up in the upper righthand box. I assume this is something very obvious but I cannot figure it out and want to make sure I am getting credit for the work I'm doing! For now, I am just saving it periodically.

**Comment by btskinner** [comment]
@taylorburtch, try this:

1. Drag the homework script (I assume is called something like `dw_one_hw_<last_name>.R`) out of your class repo and drop it on your Desktop (or somewhere safe so you still have it). It is now **not** in your class repo.
1. See if the git pane in RStudio notices that it's gone. If so, stage the removal, commit, and push (you may need to pull before pushing since I added some files yesterday). If not, don't worry about it. Either way, close RStudio.
1. Reopen RStudio into your project and drag/drop your homework script back into your scripts folder. Hopefully it will pop up in the git pane to add.

TBH, this is the git version of "turning it off and turning it back on." But sometimes it works best. Let me know; if not, we'll try something else.

**Comment by taylorburtch** [comment]
I'm not sure if I followed your directions exactly, but I got it to work by combining these comments and playing with it some more! Thank you!

**Comment by btskinner** [comment]
Great! I'll close this now, but reopen if you have trouble again.
